# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tadaa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cell',
            old_name='entity_run',
            new_name='entity_ann',
        ),
    ]
